id = "defold"
name = "Defold"
description = "Defold game engine support with bundled API docs, Lua language server, and 20+ code snippets"
version = "0.1.0"
schema_version = 1
authors = ["Dmitry Paramonov <asmatic075@gmail.com>"]
repository = "https://github.com/whiterabbit1983/zed-defold"
keywords = ["defold", "lua", "game-development", "game-engine"]

[language_servers.lua-language-server]
name = "Lua Language Server"
language = "Defold"

