id = "defold"
name = "Defold"
description = "Defold game engine support with bundled API docs, Lua language server, and code snippets"
version = "0.1.2"
schema_version = 1
authors = ["Dmitry Paramonov <asmatic075@gmail.com>"]
repository = "https://github.com/whiterabbit1983/zed-defold"
keywords = ["defold", "lua", "game-development", "game-engine"]

[grammars.lua]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-lua"
commit = "d76023017f7485eae629cb60d406c7a1ca0f40c9"

[language_servers.lua-language-server]
name = "Lua Language Server"
language = "Defold"
